apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alpha-metric-spammer-1
  namespace: project-alpha
spec:
  selector:
    matchLabels:
      app: alpha-metric-spammer-1
  namespaceSelector:
    matchNames:
    - project-alpha
  endpoints:
  - port: web
    interval: 5s
