apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-metric-spammer-1
  namespace: project-alpha
  labels:
    name: alpha-metric-spammer-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: alpha-metric-spammer-1
  template:
    metadata:
      labels:
        name: alpha-metric-spammer-1
    spec:
      containers:
      - name: alpha-metric-spammer-1
        image: topping/metricspammer:1.0.0
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
        ports:
        - containerPort: 8001
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: false
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8001
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8001
          initialDelaySeconds: 180
          periodSeconds: 3