apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-metric-spammer-1
  namespace: project-alpha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpha-metric-spammer-1
  template:
    metadata:
      labels:
        app: alpha-metric-spammer-1
    spec:
      containers:
      - name: alpha-metric-spammer-1
        image: topping/metricspammer:1.0.0
        ports:
        - name: metrics
          containerPort: 8001
        envFrom:
        - configMapRef:
            name: metric-spammer-1-config
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 3