apiVersion: v1
kind: Service
metadata:
  name: alpha-metric-spammer-1
  namespace: project-alpha
  labels:
    name: alpha-metric-spammer-1
spec:
  ports:
    # the port that this service should serve on
  - port: 9001
    targetPort: 8001
  selector:
    name: alpha-metric-spammer-1