apiVersion: v1
kind: Service
metadata:
  name: alpha-metric-spammer-1
  namespace: project-alpha
  labels:
    shouldMonitor: heckyeah
    monitoring: true
spec:
  ports:
  - name: metrics
    port: 8001
  selector:
    name: alpha-metric-spammer-1