## App of Apps for Project Beta
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # Source of the application manifests
  source:
    path: src/overlays/local