apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-alpha
  namespace: argocd
spec:
  description: Project-Alpha
  sourceRepos:
  - 'git@github.com:Gatefail/argocd-setup.git'
  - 'git@github.com:Gatefail/argocd-applications.git'
  # Only permit applications to deploy to the argocd namespace in the same cluster
  destinations:
  - namespace: project-alpha
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  ## Allow creation of namespace as cluster-wide resource
  clusterResourceWhitelist:
  - group: ''
    kind: 'Namespace'
  roles:
  # sync privileges that can be granted to a CI system user
  - name: project-alpha-sync-ci-role
    description: Sync privileges for project-alpha
    policies:
    - p, proj:project-alpha:project-alpha-sync-ci-role, applications, sync, project-alpha/project-alpha-app, allow