apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-metric-spammer-2
  namespace: project-alpha
  labels:
    shouldMonitor: heckyeah
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpha-metric-spammer-2
  template:
    metadata:
      labels:
        app: alpha-metric-spammer-2
        shouldMonitor: heckyeah
    spec:
      containers:
      - name: alpha-metric-spammer-2
        image: topping/metricspammer:1.0.0
        envFrom:
        - configMapRef:
            name: metric-spammer-2-config
        ports:
        - name: metrics
          containerPort: 8001
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 3