apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alpha-ns-monitor
  namespace: project-alpha
  labels:
    release: prometheus-operator
    monitoring: true
spec:
  selector:
    matchLabels:
      shouldMonitor: heckyeah
  # namespaceSelector:
  #  matchNames:
  #  - project-alpha
  endpoints:
  - port: metrics
    interval: 5s
