apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alpha-ns-monitor
  namespace: project-alpha
  labels:
    release: prometheus-operator
    monitoring: true
spec:
  targetLabels:
    - shouldMonitor
  selector:
    matchLabels:
      shouldMonitor: heckyeah
  endpoints:
  - port: metrics