apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alpha-ns-monitor
  namespace: project-alpha
  labels:
    release: prometheus-operator
    monitoring: true
spec:
  selector:
    matchLabels:
      app: alpha-metric-spammer-1
      app: alpha-metric-spammer-2
  endpoints:
  - port: metrics