apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alpha-ns-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
    - project-alpha
  selector:
    matchLabels:
      app: alpha-metric-spammer-1
  endpoints:
  - port: metrics