## App of Apps for Project Alpha
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-alpha-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: project-alpha
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-alpha
  # Source of the application manifests
  source:
    repoURL: git@github.com:Gatefail/argocd-applications.git
    targetRevision: HEAD
    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: project-alpha