## App of Apps for Project Alpha
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: project-alpha

  # Source of the application manifests
  source:
    path: project-alpha
    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: project-alpha