## App of Apps for Project Alpha
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatefail
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: project-alpha
  # Source of the application manifests
  source:
    repoURL: git@github.com:Gatefail/argocd-applications.git
    targetRevision: HEAD
    
  # Sync policy
  syncPolicy:
    manual:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).