apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
    - ./metric-spammer-1
    - ./metric-spammer-2
    - ./project-beta-app.yaml
    - ./project-beta-ns.yaml
    - ./project-beta-proj.yaml