## App of Apps for Project beta
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-beta-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: project-beta

  # Source of the application manifests
  source:
    repoURL: git@github.com:Gatefail/argocd-applications.git
    targetRevision: HEAD
    path: project-beta
    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: project-beta

  # Sync policy
  syncPolicy:
    manual:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).