apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
  namespace: argocd
spec:
  description: Project-Beta
  # Only permit applications to deploy to the argocd namespace in the same cluster
  destinations:
  - namespace: project-beta
    server: https://kubernetes.default.svc
  ## Allow creation of namespace as cluster-wide resource
  clusterResourceWhitelist:
  - group: ''
    kind: 'Namespace'
  roles:
  # sync privileges that can be granted to a CI system user
  - name: project-beta-sync-ci-role
    description: Sync privileges for project-beta
    policies:
    - p, proj:project-veta:project-beta-sync-ci-role, applications, sync, project-beta/project-beta-app, allow